[project]
version = "0.1.0"
name = "zx_utils"
cincludes = ["deps"]
pkgconfig = []
cflags = []
lflags = []
cobjects = [
  "deps/list/list.c",
  "deps/list/list_node.c",
  "deps/list/list_iterator.c",
]

[variants]
default = []

[dependencies]
