[project]
version = "0.1.0"
name = "zxhttp"
cincludes = ["-pthread"]
cobjects = []
pkgconfig = []
cflags = []
lflags = []

[variants]
default = []

[dependencies]
curl = "*"
list = "*"
log = "*"
utils = "*"
