name: Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 'Download ZZ'
      run: |
        git clone https://github.com/aep/zz.git
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --path zz
    - name: 'Install System Dependencies'
      run: |
        sudo apt install -y z3 libcurl4 libcurl4-openssl-dev
    - name: 'Tests'
      run: |
        make test
